"""initial_schema

Revision ID: b9c2401a0dfe
Revises: 
Create Date: 2026-09-29 18:56:12.998618
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models.types

revision: str = 'b9c2401a0dfe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('waste_categories',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_hazard', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('collector_profiles',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('collector_type', sa.String(length=50), nullable=False),
    sa.Column('national_id_number', sa.String(length=100), nullable=True),
    sa.Column('national_id_type', sa.String(length=50), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('trust_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_lots_collected', sa.Integer(), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_profiles_user_id'), 'collector_profiles', ['user_id'], unique=True)
    op.create_table('materials',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('category_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_unit', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['waste_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('recycler_companies',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=250), nullable=False),
    sa.Column('trade_license_number', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('cpcb_registration_no', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('operating_status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lots',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('lot_code', sa.String(length=50), nullable=False),
    sa.Column('collector_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('designated_facility_id', src.models.types.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_estimated_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('total_verified_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('agreed_price_per_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('weighbridge_slip_number', sa.String(length=100), nullable=True),
    sa.Column('verified_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('origin_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('origin_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('origin_address', sa.Text(), nullable=True),
    sa.Column('offline_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['collector_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_collector_id'), 'lots', ['collector_id'], unique=False)
    op.create_index(op.f('ix_lots_lot_code'), 'lots', ['lot_code'], unique=True)
    op.create_index(op.f('ix_lots_status'), 'lots', ['status'], unique=False)
    op.create_table('material_price_bands',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('material_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('min_price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('benchmark_price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recycler_facilities',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('recycler_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('facility_name', sa.String(length=200), nullable=False),
    sa.Column('address_line1', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('daily_capacity_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('accepts_hazardous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recycler_id'], ['recycler_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorization_records',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('facility_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('authorization_type', sa.String(length=80), nullable=False),
    sa.Column('authorization_number', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['recycler_facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custody_events',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('lot_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', src.models.types.GUID(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_payload_json', sa.JSON(), nullable=False),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=False),
    sa.Column('current_event_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handover_records',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('lot_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('collector_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('reference_no', sa.String(length=80), nullable=False),
    sa.Column('requested_recycler_id', sa.String(length=100), nullable=False),
    sa.Column('declared_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('declared_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('collector_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recycler_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['collector_profiles.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handover_records_collector_id'), 'handover_records', ['collector_id'], unique=False)
    op.create_index(op.f('ix_handover_records_lot_id'), 'handover_records', ['lot_id'], unique=False)
    op.create_index(op.f('ix_handover_records_reference_no'), 'handover_records', ['reference_no'], unique=True)
    op.create_index(op.f('ix_handover_records_status'), 'handover_records', ['status'], unique=False)
    op.create_table('lot_items',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('lot_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('material_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('estimated_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('verified_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ai_confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('detected_hazard', sa.String(length=50), nullable=False),
    sa.Column('safety_guidance_id', src.models.types.GUID(length=36), nullable=True),
    sa.Column('unit_price_estimated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price_verified', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('subtotal_estimated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_final', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_items_lot_id'), 'lot_items', ['lot_id'], unique=False)
    op.create_index(op.f('ix_lot_items_material_id'), 'lot_items', ['material_id'], unique=False)
    op.create_table('recycler_payments',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('lot_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('recycler_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gateway_reference', sa.String(length=100), nullable=False),
    sa.Column('weighbridge_slip', sa.String(length=100), nullable=False),
    sa.Column('custody_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_reference', name='uq_recycler_payment_gateway_reference')
    )
    op.create_table('lot_images',
    sa.Column('id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('lot_id', src.models.types.GUID(length=36), nullable=False),
    sa.Column('lot_item_id', src.models.types.GUID(length=36), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_proof_of_collection', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_item_id'], ['lot_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_images_image_hash'), 'lot_images', ['image_hash'], unique=False)
    op.create_index(op.f('ix_lot_images_lot_id'), 'lot_images', ['lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_images_lot_id'), table_name='lot_images')
    op.drop_index(op.f('ix_lot_images_image_hash'), table_name='lot_images')
    op.drop_table('lot_images')
    op.drop_table('recycler_payments')
    op.drop_index(op.f('ix_lot_items_material_id'), table_name='lot_items')
    op.drop_index(op.f('ix_lot_items_lot_id'), table_name='lot_items')
    op.drop_table('lot_items')
    op.drop_index(op.f('ix_handover_records_status'), table_name='handover_records')
    op.drop_index(op.f('ix_handover_records_reference_no'), table_name='handover_records')
    op.drop_index(op.f('ix_handover_records_lot_id'), table_name='handover_records')
    op.drop_index(op.f('ix_handover_records_collector_id'), table_name='handover_records')
    op.drop_table('handover_records')
    op.drop_table('custody_events')
    op.drop_table('authorization_records')
    op.drop_table('recycler_facilities')
    op.drop_table('material_price_bands')
    op.drop_index(op.f('ix_lots_status'), table_name='lots')
    op.drop_index(op.f('ix_lots_lot_code'), table_name='lots')
    op.drop_index(op.f('ix_lots_collector_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_table('recycler_companies')
    op.drop_table('materials')
    op.drop_index(op.f('ix_collector_profiles_user_id'), table_name='collector_profiles')
    op.drop_table('collector_profiles')
    op.drop_table('waste_categories')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
